@startuml
!theme plain
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName Arial
skinparam ArrowFontSize 11

start
:checkingCredentials();

note right
  Inicio del proceso de autenticación
  Cambia el estado a "checking"
end note

partition "Bloque Try" {
  :signInWithEmailAndPassword();
  
  if (¿Credenciales válidas?) then (Sí)
    if (¿Email verificado?) then (Sí)
      :dispatch(login());
      note right: Almacena datos del usuario
    else (No)
      :sendEmailVerification();
      :FirebaseAuth.signOut();
      :dispatch(logout());
      note right: Con mensaje: "Verifica tu correo"
    endif
  else (No)
    :Error en inicio de sesión;
    :dispatch(logout());
  endif
}

partition "Bloque Catch" {
  :Manejo de error;
  note right: Captura cualquier excepción
  :dispatch(logout());
  note right: Con mensaje: "Error al iniciar sesión"
}

stop

@enduml